version: 2
jobs:
  build:
    working_directory: ~/graphql-cli-prepare
    docker:
      - image: circleci/node:latest@sha256:923015eaccb7e70e457bd13e0b7b604bc9378bdd837afb1b35331f8447c34320
    steps:
      - checkout
      - run: sudo npm install -g yarn semantic-release
      - run: yarn install
      - run: yarn test
      - run: semantic-release
